### ISSUE TITLE
OG画像生成について

### ISSUE THREAD

**Issue by Yephy** [JY8752/zenn_article#1]
素晴らしい記事です。この方法に従って正常に展開されました。
ただし、質問したいことがあります。
記事ページのメタデータでは、twitter 画像と og 画像の API インターフェイスが提供されます。
https://ogp-generate.j-y-87524086.workers.dev?msg=${title}
導入にはどのオープンソース プログラムが使用されましたか?どうもありがとうございます！

**Comment by JY8752** [comment]
@Yephy 

質問ありがとうございます。
以下のリンクが参考になるかもしれません。

https://github.com/JY8752/my-blog/tree/main/cloudflare/workers/ogp-generate

vercel/satoriを使って動的に画像を生成したものをCloudflare Workersで返しています。

> Thank you for your question. The following link might be helpful:
> https://github.com/JY8752/my-blog/tree/main/cloudflare/workers/ogp-generate
> We are using vercel/satori to dynamically generate images and return them via Cloudflare Workers.

**Comment by Yephy** [comment]
早速のご返信、誠にありがとうございます。これで私の問題は解決しました。ありがとうございます!
